### ISSUE TITLE
Required version of rawpi not available for windows

### ISSUE THREAD

**Issue by limabravo7** [yux1991/PyRHEED#4]
Dear Yu,

I was trying to install the program with python version 3.7.4 from inside my IDE. Unfortunately the required version of rawpy is not available for my platform (Windows 11 64bit). This is the ouput, that I get from my IDE after installing the requirements.txt:

``
ERROR: Could not find a version that satisfies the requirement rawpy==0.17.2 (from versions: 0.13.0, 0.13.1, 0.14.0a1)
ERROR: No matching distribution found for rawpy==0.17.2
``

Using the newest version of rawpy, which is given above (0.14.0.a1) leads to an error as expected, due to some missing DLLs.
Do you have an idea on how to solve this? Are there maybe plans to move to a newer version of python in the near future anyway?

Right now I'm still unexperienced regarding debugging, but I'd be motivated to dig in and look for a solution, maybe even to transfer it to a newer version. Maybe you have an idea for me, on where to start?

Thanks, and best regards,
Leon

**Comment by yux1991** [comment]
Hi Leon, thanks for your interest in this project. I tested on my PC which is also Windows 11 64 bit but I didn't encounter this error. I'd recommend create a virtual environment and then run setup.py in this new environment to see if you still get this error.

**Comment by yux1991** [comment]
@limabravo7 I encountered the same issue as you on Ubuntu. Just remove the version specification for rawpy in the requirements.txt by changing "rawpy==0.17.2" to "rawpy" would work for me.

**Comment by limabravo7** [comment]
Dear Yu, thanks to Nills in our team we manged to solve the problem by porting to Python 3.11 alongside with PyQT6. Feel free to checkout the repo, that Nils linked in the other comment.

**Comment by yux1991** [comment]
That's great to hear!
